name: Test Build
on: 
  push:
    branches: 
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set WIP to Draft
      uses: wip/action@v1.0.0
    - uses: cachix/install-nix-action@v8
    - run: bash ./generate_test_conf.sh > default.nix 
    - run: nix-build
